apiVersion: v1
kind: Namespace
metadata:
  name: foobar
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: foobar
  labels:
    appId: appId
spec:
  ports:
  - port: 8080
    name: http
  selector:
    appId: appId
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appId: appId
    envId: envId
    ownerId: foobar
  name: app-deploy
  namespace: foobar
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      appId: appId
      envId: envId
      ownerId: foobar
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        appId: appId
        envId: envId
        ownerId: foobar
    spec:
      automountServiceAccountToken: true
      containers:
      - env:
        - name: QOVERY_BRANCH_NAME
          value: master
        - name: QOVERY_IS_PRODUCTION
          value: "True"
        image: jmalloc/echo-server
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        name: app-container
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 256m
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts: []
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes: []
#---
#apiVersion: "security.istio.io/v1beta1"
#kind: "PeerAuthentication"
#metadata:
#  name: "foobar"
#  namespace: foobar
#spec:
#  mtls:
#    mode: STRICT
#---
#apiVersion: security.istio.io/v1beta1
#kind: AuthorizationPolicy
#metadata:
#  name: namespace-isolation
#  namespace: foobar
#spec:
#  action: ALLOW
#  rules:
#  - from:
#    - source:
#        namespaces:
#        - foobar
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: app-issuer-foobar
  # NOTE(foobar): issuer must be in istio-system, this sucks for isolation...
  namespace: istio-system
  labels:
    ownerId: foobar
    fqdn: kind.foobar.net
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mabaakouk@qovery.com
    privateKeySecretRef:
      name: kind-issuer-key-foobar
    solvers:
      - http01:
          ingress:
            class: istio
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: app-gateway-cert-foobar
  # NOTE(foobar): issuer must be in istio-system, this sucks for isolation...
  namespace: istio-system
  labels:
    ownerId: foobar
    fqdn: "app.kin.foobar.net"
spec:
  secretName: app-gateway-cert-secret-foobar
  issuerRef:
    name: app-issuer-foobar
    kind: Issuer
  dnsNames:
    - foobar.kind.sileht.net
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: app-gateway
  namespace: foobar
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "foobar.kind.sileht.net"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: app-gateway-cert-secret-foobar
    hosts:
    - "foobar.kind.sileht.net"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-virtualservice
  namespace: foobar
spec:
  hosts:
  - "foobar.kind.sileht.net"
  gateways:
  - app-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: app-service
        port:
          number: 8080
